/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as MemberRecordsRouteImport } from './routes/member.records'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberMessagesRouteImport } from './routes/member.messages'
import { Route as MemberHomeRouteImport } from './routes/member.home'
import { Route as MemberExercisesRouteImport } from './routes/member.exercises'
import { Route as MemberBookingRouteImport } from './routes/member.booking'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as MemberExercisesExerciseIdRouteImport } from './routes/member.exercises.$exerciseId'
import { Route as AppMembersMemberIdRouteImport } from './routes/_app/members.$memberId'
import { Route as AppAdminWorkoutsRouteImport } from './routes/_app/admin.workouts'
import { Route as AppAdminTrainersRouteImport } from './routes/_app/admin.trainers'
import { Route as AppAdminStatsRouteImport } from './routes/_app/admin.stats'
import { Route as AppAdminRequestsRouteImport } from './routes/_app/admin.requests'
import { Route as AppAdminNoticeRouteImport } from './routes/_app/admin.notice'
import { Route as AppAdminMessagesRouteImport } from './routes/_app/admin.messages'
import { Route as AppAdminExercisesRouteImport } from './routes/_app/admin.exercises'
import { Route as AppAdminApprovalsRouteImport } from './routes/_app/admin.approvals'
import { Route as AppAdminTrainersTrainerIdRouteImport } from './routes/_app/admin.trainers.$trainerId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MemberRecordsRoute = MemberRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMessagesRoute = MemberMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MemberRoute,
} as any)
const MemberHomeRoute = MemberHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MemberRoute,
} as any)
const MemberExercisesRoute = MemberExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBookingRoute = MemberBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => MemberRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const MemberExercisesExerciseIdRoute =
  MemberExercisesExerciseIdRouteImport.update({
    id: '/$exerciseId',
    path: '/$exerciseId',
    getParentRoute: () => MemberExercisesRoute,
  } as any)
const AppMembersMemberIdRoute = AppMembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppAdminWorkoutsRoute = AppAdminWorkoutsRouteImport.update({
  id: '/admin/workouts',
  path: '/admin/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTrainersRoute = AppAdminTrainersRouteImport.update({
  id: '/admin/trainers',
  path: '/admin/trainers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStatsRoute = AppAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRequestsRoute = AppAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNoticeRoute = AppAdminNoticeRouteImport.update({
  id: '/admin/notice',
  path: '/admin/notice',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMessagesRoute = AppAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExercisesRoute = AppAdminExercisesRouteImport.update({
  id: '/admin/exercises',
  path: '/admin/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTrainersTrainerIdRoute =
  AppAdminTrainersTrainerIdRouteImport.update({
    id: '/$trainerId',
    path: '/$trainerId',
    getParentRoute: () => AppAdminTrainersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/members': typeof AppMembersRouteWithChildren
  '/member/booking': typeof MemberBookingRoute
  '/member/exercises': typeof MemberExercisesRouteWithChildren
  '/member/home': typeof MemberHomeRoute
  '/member/messages': typeof MemberMessagesRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/records': typeof MemberRecordsRoute
  '/member/': typeof MemberIndexRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/exercises': typeof AppAdminExercisesRoute
  '/admin/messages': typeof AppAdminMessagesRoute
  '/admin/notice': typeof AppAdminNoticeRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/stats': typeof AppAdminStatsRoute
  '/admin/trainers': typeof AppAdminTrainersRouteWithChildren
  '/admin/workouts': typeof AppAdminWorkoutsRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
  '/member/exercises/$exerciseId': typeof MemberExercisesExerciseIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/trainers/$trainerId': typeof AppAdminTrainersTrainerIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/members': typeof AppMembersRouteWithChildren
  '/member/booking': typeof MemberBookingRoute
  '/member/exercises': typeof MemberExercisesRouteWithChildren
  '/member/home': typeof MemberHomeRoute
  '/member/messages': typeof MemberMessagesRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/records': typeof MemberRecordsRoute
  '/': typeof AppIndexRoute
  '/member': typeof MemberIndexRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/exercises': typeof AppAdminExercisesRoute
  '/admin/messages': typeof AppAdminMessagesRoute
  '/admin/notice': typeof AppAdminNoticeRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/stats': typeof AppAdminStatsRoute
  '/admin/trainers': typeof AppAdminTrainersRouteWithChildren
  '/admin/workouts': typeof AppAdminWorkoutsRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
  '/member/exercises/$exerciseId': typeof MemberExercisesExerciseIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/trainers/$trainerId': typeof AppAdminTrainersTrainerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/members': typeof AppMembersRouteWithChildren
  '/member/booking': typeof MemberBookingRoute
  '/member/exercises': typeof MemberExercisesRouteWithChildren
  '/member/home': typeof MemberHomeRoute
  '/member/messages': typeof MemberMessagesRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/records': typeof MemberRecordsRoute
  '/_app/': typeof AppIndexRoute
  '/member/': typeof MemberIndexRoute
  '/_app/admin/approvals': typeof AppAdminApprovalsRoute
  '/_app/admin/exercises': typeof AppAdminExercisesRoute
  '/_app/admin/messages': typeof AppAdminMessagesRoute
  '/_app/admin/notice': typeof AppAdminNoticeRoute
  '/_app/admin/requests': typeof AppAdminRequestsRoute
  '/_app/admin/stats': typeof AppAdminStatsRoute
  '/_app/admin/trainers': typeof AppAdminTrainersRouteWithChildren
  '/_app/admin/workouts': typeof AppAdminWorkoutsRoute
  '/_app/members/$memberId': typeof AppMembersMemberIdRoute
  '/member/exercises/$exerciseId': typeof MemberExercisesExerciseIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/trainers/$trainerId': typeof AppAdminTrainersTrainerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/member'
    | '/reset-password'
    | '/attendance'
    | '/calendar'
    | '/members'
    | '/member/booking'
    | '/member/exercises'
    | '/member/home'
    | '/member/messages'
    | '/member/profile'
    | '/member/records'
    | '/member/'
    | '/admin/approvals'
    | '/admin/exercises'
    | '/admin/messages'
    | '/admin/notice'
    | '/admin/requests'
    | '/admin/stats'
    | '/admin/trainers'
    | '/admin/workouts'
    | '/members/$memberId'
    | '/member/exercises/$exerciseId'
    | '/admin/'
    | '/admin/trainers/$trainerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/attendance'
    | '/calendar'
    | '/members'
    | '/member/booking'
    | '/member/exercises'
    | '/member/home'
    | '/member/messages'
    | '/member/profile'
    | '/member/records'
    | '/'
    | '/member'
    | '/admin/approvals'
    | '/admin/exercises'
    | '/admin/messages'
    | '/admin/notice'
    | '/admin/requests'
    | '/admin/stats'
    | '/admin/trainers'
    | '/admin/workouts'
    | '/members/$memberId'
    | '/member/exercises/$exerciseId'
    | '/admin'
    | '/admin/trainers/$trainerId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/member'
    | '/reset-password'
    | '/_app/attendance'
    | '/_app/calendar'
    | '/_app/members'
    | '/member/booking'
    | '/member/exercises'
    | '/member/home'
    | '/member/messages'
    | '/member/profile'
    | '/member/records'
    | '/_app/'
    | '/member/'
    | '/_app/admin/approvals'
    | '/_app/admin/exercises'
    | '/_app/admin/messages'
    | '/_app/admin/notice'
    | '/_app/admin/requests'
    | '/_app/admin/stats'
    | '/_app/admin/trainers'
    | '/_app/admin/workouts'
    | '/_app/members/$memberId'
    | '/member/exercises/$exerciseId'
    | '/_app/admin/'
    | '/_app/admin/trainers/$trainerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/member/records': {
      id: '/member/records'
      path: '/records'
      fullPath: '/member/records'
      preLoaderRoute: typeof MemberRecordsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/messages': {
      id: '/member/messages'
      path: '/messages'
      fullPath: '/member/messages'
      preLoaderRoute: typeof MemberMessagesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/home': {
      id: '/member/home'
      path: '/home'
      fullPath: '/member/home'
      preLoaderRoute: typeof MemberHomeRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/exercises': {
      id: '/member/exercises'
      path: '/exercises'
      fullPath: '/member/exercises'
      preLoaderRoute: typeof MemberExercisesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/booking': {
      id: '/member/booking'
      path: '/booking'
      fullPath: '/member/booking'
      preLoaderRoute: typeof MemberBookingRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/member/exercises/$exerciseId': {
      id: '/member/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/member/exercises/$exerciseId'
      preLoaderRoute: typeof MemberExercisesExerciseIdRouteImport
      parentRoute: typeof MemberExercisesRoute
    }
    '/_app/members/$memberId': {
      id: '/_app/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AppMembersMemberIdRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/_app/admin/workouts': {
      id: '/_app/admin/workouts'
      path: '/admin/workouts'
      fullPath: '/admin/workouts'
      preLoaderRoute: typeof AppAdminWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/trainers': {
      id: '/_app/admin/trainers'
      path: '/admin/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AppAdminTrainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/stats': {
      id: '/_app/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AppAdminStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/requests': {
      id: '/_app/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AppAdminRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notice': {
      id: '/_app/admin/notice'
      path: '/admin/notice'
      fullPath: '/admin/notice'
      preLoaderRoute: typeof AppAdminNoticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/messages': {
      id: '/_app/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AppAdminMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/exercises': {
      id: '/_app/admin/exercises'
      path: '/admin/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AppAdminExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approvals': {
      id: '/_app/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/trainers/$trainerId': {
      id: '/_app/admin/trainers/$trainerId'
      path: '/$trainerId'
      fullPath: '/admin/trainers/$trainerId'
      preLoaderRoute: typeof AppAdminTrainersTrainerIdRouteImport
      parentRoute: typeof AppAdminTrainersRoute
    }
  }
}

interface AppMembersRouteChildren {
  AppMembersMemberIdRoute: typeof AppMembersMemberIdRoute
}

const AppMembersRouteChildren: AppMembersRouteChildren = {
  AppMembersMemberIdRoute: AppMembersMemberIdRoute,
}

const AppMembersRouteWithChildren = AppMembersRoute._addFileChildren(
  AppMembersRouteChildren,
)

interface AppAdminTrainersRouteChildren {
  AppAdminTrainersTrainerIdRoute: typeof AppAdminTrainersTrainerIdRoute
}

const AppAdminTrainersRouteChildren: AppAdminTrainersRouteChildren = {
  AppAdminTrainersTrainerIdRoute: AppAdminTrainersTrainerIdRoute,
}

const AppAdminTrainersRouteWithChildren =
  AppAdminTrainersRoute._addFileChildren(AppAdminTrainersRouteChildren)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppMembersRoute: typeof AppMembersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminExercisesRoute: typeof AppAdminExercisesRoute
  AppAdminMessagesRoute: typeof AppAdminMessagesRoute
  AppAdminNoticeRoute: typeof AppAdminNoticeRoute
  AppAdminRequestsRoute: typeof AppAdminRequestsRoute
  AppAdminStatsRoute: typeof AppAdminStatsRoute
  AppAdminTrainersRoute: typeof AppAdminTrainersRouteWithChildren
  AppAdminWorkoutsRoute: typeof AppAdminWorkoutsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppMembersRoute: AppMembersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminExercisesRoute: AppAdminExercisesRoute,
  AppAdminMessagesRoute: AppAdminMessagesRoute,
  AppAdminNoticeRoute: AppAdminNoticeRoute,
  AppAdminRequestsRoute: AppAdminRequestsRoute,
  AppAdminStatsRoute: AppAdminStatsRoute,
  AppAdminTrainersRoute: AppAdminTrainersRouteWithChildren,
  AppAdminWorkoutsRoute: AppAdminWorkoutsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MemberExercisesRouteChildren {
  MemberExercisesExerciseIdRoute: typeof MemberExercisesExerciseIdRoute
}

const MemberExercisesRouteChildren: MemberExercisesRouteChildren = {
  MemberExercisesExerciseIdRoute: MemberExercisesExerciseIdRoute,
}

const MemberExercisesRouteWithChildren = MemberExercisesRoute._addFileChildren(
  MemberExercisesRouteChildren,
)

interface MemberRouteChildren {
  MemberBookingRoute: typeof MemberBookingRoute
  MemberExercisesRoute: typeof MemberExercisesRouteWithChildren
  MemberHomeRoute: typeof MemberHomeRoute
  MemberMessagesRoute: typeof MemberMessagesRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberRecordsRoute: typeof MemberRecordsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberBookingRoute: MemberBookingRoute,
  MemberExercisesRoute: MemberExercisesRouteWithChildren,
  MemberHomeRoute: MemberHomeRoute,
  MemberMessagesRoute: MemberMessagesRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberRecordsRoute: MemberRecordsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
